import type { Metadata } from "next";
import Link from "next/link";
import LegalDocument, { type LegalSection } from "@/components/legal/LegalDocument";
import Nav from "@/components/sections/Nav";
import Footer from "@/components/sections/Footer";
import CookieBanner from "@/components/sections/CookieBanner";

export const metadata: Metadata = { title: "Privacy Policy | The Markgent LLC", description: "How The Markgent LLC collects, uses, discloses, and safeguards your information when you visit our website or use our services." };

const sections: LegalSection[] = [
  { id: "information-we-collect", title: "Information we collect", content: <><p>Welcome to The Markgent LLC. Your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our services.</p><p>We may collect the following information:</p><ul className="list-disc space-y-2 pl-5"><li>Name</li><li>Email address</li><li>Phone number</li><li>Company name</li><li>Information you provide through our contact forms</li><li>Project details and requirements</li><li>Website usage data (such as IP address, browser type, pages visited, and device information)</li></ul><p>Please do not send passwords, payment card details, government identifiers, or other sensitive information through our contact form.</p></> },
  { id: "how-we-use", title: "How we use your information", content: <><p>We use your information to:</p><ul className="list-disc space-y-2 pl-5"><li>Respond to inquiries</li><li>Provide requested services</li><li>Communicate regarding ongoing projects</li><li>Improve our website and services</li><li>Send project updates and important notifications</li><li>Comply with legal obligations</li></ul><p>We do not sell or rent your personal information to third parties.</p></> },
  { id: "cookies", title: "Cookies", content: <><p>Our website may use cookies and similar technologies to improve your browsing experience, analyze website traffic, and remember user preferences.</p><p>You may disable cookies through your browser settings; however, some features of the website may not function properly. For a fuller explanation of the categories we use and how to manage them, see our <Link href="/cookie-policy" className="font-semibold text-ink underline underline-offset-4">Cookie Policy</Link>.</p></> },
  { id: "third-party-services", title: "Third-party services", content: <><p>We may use trusted third-party providers, including but not limited to:</p><ul className="list-disc space-y-2 pl-5"><li>Payment processors</li><li>Website analytics providers</li><li>Email service providers</li><li>Cloud hosting services</li></ul><p>These providers only receive information necessary to perform their services and are expected to protect your data.</p></> },
  { id: "data-security", title: "Data security", content: <><p>We implement reasonable administrative, technical, and organizational measures to protect your personal information from unauthorized access, disclosure, or misuse.</p><p>However, no method of electronic transmission or storage is completely secure.</p></> },
  { id: "data-retention", title: "Data retention", content: <p>We retain personal information only as long as necessary to provide our services, comply with legal obligations, resolve disputes, and enforce our agreements.</p> },
  { id: "your-rights", title: "Your rights", content: <><p>Depending on your location, you may have the right to:</p><ul className="list-disc space-y-2 pl-5"><li>Request access to your personal information</li><li>Request corrections</li><li>Request deletion of your information</li><li>Withdraw consent where applicable</li></ul><p>To exercise these rights, please contact us at <a className="font-semibold text-ink underline underline-offset-4" href="mailto:director@themarkgentllc.com">director@themarkgentllc.com</a>. We will verify and respond to requests as required by applicable law, and we will not discriminate against you for exercising a legal privacy right.</p></> },
  { id: "childrens-privacy", title: "Children's privacy", content: <><p>Our services are intended for individuals and businesses aged 18 years or older. We do not knowingly collect information from children under 13.</p><p>If you contact us from outside the United States, your information may be processed in the United States, where privacy laws may differ from those in your jurisdiction.</p></> },
  { id: "changes", title: "Changes to this policy", content: <p>We may update this Privacy Policy from time to time. Updates become effective immediately upon posting on this page. The effective date above identifies the latest version.</p> },
  { id: "contact", title: "Contact us", content: <><p>If you have questions regarding this Privacy Policy, please contact:</p><p><strong className="font-semibold text-ink">The Markgent LLC</strong><br />Email: <a className="font-semibold text-ink underline underline-offset-4" href="mailto:director@themarkgentllc.com">director@themarkgentllc.com</a><br />Website: <a className="font-semibold text-ink underline underline-offset-4" href="https://themarkgent.com">themarkgent.com</a><br />Location: United States — remote service business</p></> },
];

export default function PrivacyPolicyPage() { return <><Nav /><LegalDocument eyebrow="Legal" title="Privacy Policy" summary="How The Markgent LLC collects, uses, discloses, and safeguards your information when you visit our website or use our services." sections={sections} /><Footer /><CookieBanner /></>; }
