import type { Metadata } from "next";
import LegalDocument, { type LegalSection } from "@/components/legal/LegalDocument";
import Nav from "@/components/sections/Nav";
import Footer from "@/components/sections/Footer";
import CookieBanner from "@/components/sections/CookieBanner";

export const metadata: Metadata = { title: "Privacy Policy | The Markgent LLC", description: "How The Markgent LLC collects, uses, shares, and protects information." };

const sections: LegalSection[] = [
  { id: "who-we-are", title: "Who we are", content: <p>This Privacy Policy describes the information practices of The Markgent LLC, a United States-registered digital marketing and e-commerce services business. It applies to this website and inquiries submitted to us, but not to third-party websites or platforms we do not control.</p> },
  { id: "information-we-collect", title: "Information we collect", content: <><p>When you contact us, you may provide your name, email address, company or store name, phone number, service interests, and project details. Please do not send passwords, payment card information, government identifiers, health information, or other sensitive data through the inquiry form.</p><p>The website may also generate standard technical records through its hosting infrastructure, such as IP address, browser type, device information, requested pages, timestamps, and error logs. This website does not currently collect payments or contain advertising-tracking code.</p></> },
  { id: "contact-form", title: "How the contact form works", content: <p>The contact form prepares an email in your device&apos;s email application. The form is not submitted to or stored in this website&apos;s own database. Once you send the email, your information is handled by your email provider, our email provider, and The Markgent LLC in accordance with their respective systems and policies.</p> },
  { id: "how-we-use", title: "How we use information", content: <><p>We use information to respond to inquiries, evaluate potential projects, prepare proposals, provide contracted services, communicate about accounts and deliverables, maintain business records, secure and improve our website, comply with law, and protect our rights and users.</p><p>We do not sell personal information. We do not use inquiry details for unrelated automated decision-making.</p></> },
  { id: "sharing", title: "When information may be shared", content: <p>We may share information with service providers that support email, hosting, document storage, invoicing, professional advice, or contracted work, only as reasonably necessary for those functions. We may also disclose information when required by law, to protect rights or safety, during a business transaction, or with your direction or consent.</p> },
  { id: "cookies", title: "Cookies and similar technologies", content: <p>The current website does not intentionally set non-essential advertising cookies. Hosting and embedded third-party resources may process standard technical information needed to deliver content, prevent abuse, or measure reliability. If analytics or advertising technologies are added later, this policy and any consent controls will be updated before those tools are used where required.</p> },
  { id: "retention-security", title: "Retention and security", content: <><p>We retain inquiry and client information only as long as reasonably needed for communication, service delivery, legal obligations, dispute resolution, and legitimate business records. Retention periods vary by record and engagement.</p><p>We use reasonable administrative and technical safeguards, but no internet transmission or storage system can be guaranteed completely secure.</p></> },
  { id: "choices", title: "Your choices and rights", content: <p>You may request access to, correction of, or deletion of personal information we control, or object to certain uses, by emailing hello@themarkgent.com. We will verify and respond to requests as required by applicable law. Depending on your location, additional privacy rights may apply. We will not discriminate against you for exercising a legal privacy right.</p> },
  { id: "children-international", title: "Children and international visitors", content: <><p>Our services are directed to businesses and are not intended for children under 13. We do not knowingly collect personal information from children through this website.</p><p>If you contact us from outside the United States, your information may be processed in the United States, where privacy laws may differ from those in your jurisdiction.</p></> },
  { id: "changes-contact", title: "Changes and contact", content: <p>We may update this policy to reflect operational, legal, or technical changes. The effective date above identifies the latest version. Questions or privacy requests can be sent to <a className="font-semibold text-ink underline underline-offset-4" href="mailto:hello@themarkgent.com">hello@themarkgent.com</a>.</p> },
];

export default function PrivacyPolicyPage() { return <><Nav /><LegalDocument eyebrow="Legal" title="Privacy Policy" summary="A clear account of what information reaches us, why we use it, and the choices available to you." sections={sections} /><Footer /><CookieBanner /></>; }
