import type { Metadata } from "next";
import Link from "next/link";
import LegalDocument, { type LegalSection } from "@/components/legal/LegalDocument";
import Nav from "@/components/sections/Nav";
import Footer from "@/components/sections/Footer";
import CookieBanner from "@/components/sections/CookieBanner";

export const metadata: Metadata = { title: "Terms & Conditions | The Markgent LLC", description: "Terms governing use of The Markgent LLC website and professional services." };

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance and website use", content: <><p>These Terms & Conditions govern your use of this website and form a baseline for services provided by The Markgent LLC. By using the website, you agree to these Terms. If you engage us, the applicable proposal, statement of work, order form, or other signed agreement forms part of the contract and controls if it expressly conflicts with these website Terms.</p><p>You may use the website only for lawful purposes. You may not interfere with its operation, attempt unauthorized access, introduce malicious code, scrape it abusively, or misrepresent your identity or authority.</p></> },
  { id: "scope", title: "Scope of Services", content: <><p>We provide professional services that may include branding, social media management, product testing programs, website design, content writing, product photography and editing, customer feedback management, and Amazon PPC management.</p><p>Exact deliverables, milestones, revisions, platforms, client dependencies, timing, and fees are defined in the written proposal or statement of work. Requests outside that scope require written approval and may change fees or timelines. We do not guarantee rankings, sales, platform approvals, advertising performance, reviews, or other outcomes controlled by markets or third parties.</p></> },
  { id: "client-responsibilities", title: "Client responsibilities", content: <p>Clients must provide accurate information, timely access, approvals, source materials, account permissions, and lawful instructions. Clients represent that they have the rights needed for materials they supply. Delays, incomplete information, platform restrictions, or late approvals may extend timelines and may require rescheduling or additional fees described in the project agreement.</p> },
  { id: "payment", title: "Payment Terms", content: <><p>Fees, deposits, retainers, billing milestones, currency, taxes, and due dates are stated in the applicable proposal or invoice. Unless that document states otherwise, work may begin only after required initial payment and may be paused while an invoice is overdue.</p><p>Clients are responsible for approved third-party costs such as advertising spend, stock assets, software, printing, shipping, marketplace charges, or contractor expenses. Such costs may be required in advance and are generally non-refundable once committed. Clients must promptly report a billing concern so both parties can attempt to resolve it.</p></> },
  { id: "refunds", title: "Refund and cancellation terms", content: <p>Refunds and cancellations are governed by our <Link href="/refund-policy" className="font-semibold text-ink underline underline-offset-4">Refund Policy</Link>, our <Link href="/cancellation-policy" className="font-semibold text-ink underline underline-offset-4">Cancellation Policy</Link>, and any project-specific agreement. Because services reserve team capacity and produce custom work, completed work, accepted deliverables, elapsed retainer periods, and committed third-party costs are generally non-refundable. Nothing in these Terms limits a right that cannot legally be waived.</p> },
  { id: "intellectual-property", title: "Intellectual Property", content: <><p>Each party keeps ownership of materials, methods, templates, trademarks, software, know-how, and other intellectual property it owned or developed independently before the engagement. The client retains ownership of properly licensed materials it supplies.</p><p>Ownership or license rights in final deliverables are defined by the project agreement and take effect only after full payment. Unless expressly assigned in writing, The Markgent LLC retains its pre-existing tools, reusable systems, drafts, rejected concepts, working files, and general know-how. Third-party assets remain subject to their own licenses. The client grants us the limited rights needed to use supplied materials for the project.</p></> },
  { id: "confidentiality", title: "Confidentiality", content: <p>Each party will use reasonable care to protect non-public business, technical, customer, and commercial information received from the other and will use it only for the engagement. Confidentiality does not cover information that is public without breach, already lawfully known, independently developed, or lawfully received from another source. Disclosure may occur when required by law or to service providers who need the information and are subject to appropriate duties.</p> },
  { id: "third-parties", title: "Third-party platforms and materials", content: <p>Our services may depend on Amazon, Shopify, social networks, advertising systems, hosting providers, software, stock libraries, and other third parties. Their rules, pricing, availability, decisions, and outages are outside our control. Clients remain responsible for their accounts, platform compliance, product claims, inventory, fulfilment, and legal obligations.</p> },
  { id: "liability", title: "Disclaimers and Limitation of Liability", content: <><p>Services and this website are provided with reasonable professional care but, to the extent permitted by law, without warranties of uninterrupted availability or guaranteed commercial results. Advice and deliverables depend on information available at the time and are not legal, tax, or financial advice.</p><p>To the fullest extent permitted by law, neither party is liable for indirect, incidental, special, punitive, or consequential damages, or for lost profits, revenue, data, goodwill, or business opportunity. The Markgent LLC&apos;s aggregate liability arising from a service engagement will not exceed the fees paid for the specific services giving rise to the claim, except where applicable law prohibits that limitation. These limits do not exclude liability that cannot legally be limited.</p></> },
  { id: "termination", title: "Suspension and termination", content: <p>Either party may end an engagement as permitted by the project agreement. We may suspend or terminate work for material breach, overdue payment, unlawful instructions, security risk, abusive conduct, or failure to provide required cooperation, after reasonable notice where appropriate. Accrued payment, confidentiality, intellectual property, liability, and other provisions intended to survive will remain effective.</p> },
  { id: "general", title: "General terms and contact", content: <><p>If a provision is unenforceable, the remaining provisions remain effective. A failure to enforce a term is not a waiver. Rights and obligations may not be transferred without consent except in connection with a lawful business reorganization or sale. The project agreement will identify governing law and dispute terms where required.</p><p>We may update these website Terms prospectively. Material changes do not rewrite an existing signed project agreement unless both parties agree. Questions can be sent to <a className="font-semibold text-ink underline underline-offset-4" href="mailto:hello@themarkgent.com">hello@themarkgent.com</a>.</p></> },
];

export default function TermsPage() { return <><Nav /><LegalDocument eyebrow="Legal" title="Terms & Conditions" summary="The baseline rules for using this website and working with The Markgent LLC, subject to the details of each written project agreement." sections={sections} /><Footer /><CookieBanner /></>; }
