import type { Metadata } from "next";
import Link from "next/link";
import LegalDocument, { type LegalSection } from "@/components/legal/LegalDocument";
import Nav from "@/components/sections/Nav";
import Footer from "@/components/sections/Footer";
import CookieBanner from "@/components/sections/CookieBanner";

export const metadata: Metadata = { title: "Refund Policy | The Markgent LLC", description: "Refund eligibility, cancellation, non-refundable services, and processing timeframes for The Markgent LLC services." };

const sections: LegalSection[] = [
  { id: "overview", title: "Policy overview", content: <p>The Markgent LLC provides customized professional services rather than physical products. This policy explains the general handling of cancellation and refund requests. A signed proposal, statement of work, or other written agreement may include project-specific terms; those terms control where they expressly differ from this policy. Mandatory legal rights remain unaffected.</p> },
  { id: "eligibility", title: "Refund eligibility", content: <><p>A payment may be eligible for a full or partial refund when we cancel the project without completing the paid work, when duplicate or incorrect billing occurs, or when a client cancels before work begins and before costs or team capacity have been committed.</p><p>After work begins, any refund is generally limited to the unearned portion of prepaid fees after deducting completed work, reserved capacity, approved expenses, and non-recoverable third-party costs. Eligibility is assessed against the agreed scope, project records, approvals, and work delivered at the cancellation date.</p></> },
  { id: "cancellation", title: "Cancellation process", content: <><p>Send a cancellation request to <a className="font-semibold text-ink underline underline-offset-4" href="mailto:hello@themarkgent.com?subject=Cancellation%20request">hello@themarkgent.com</a> from an authorized client email address. Include the client or business name, project or invoice reference, service being cancelled, requested cancellation date, and reason for the request.</p><p>Notice periods and the terms for ending project-based or recurring work are set out in our <Link href="/cancellation-policy" className="font-semibold text-ink underline underline-offset-4">Cancellation Policy</Link>. Cancellation is effective when we confirm it in writing, unless applicable law requires otherwise. Clients remain responsible for work performed and costs committed before the effective cancellation date. We will provide available completed work after outstanding amounts are settled and subject to the project&apos;s intellectual-property terms.</p></> },
  { id: "non-refundable", title: "Non-refundable services and costs", content: <><p>The following are generally non-refundable once incurred or provided:</p><ul className="list-disc space-y-2 pl-5"><li>Completed, delivered, or approved work and consumed revision rounds.</li><li>Deposits expressly identified as non-refundable or used to reserve production capacity.</li><li>Retainer periods or scheduled capacity that have already started.</li><li>Custom strategy, research, writing, design, photography, editing, campaign setup, or development already performed.</li><li>Advertising spend, platform charges, domains, hosting, software, stock assets, shipping, printing, tester-related costs, and other third-party commitments.</li><li>Rush fees and work delayed or made unusable by inaccurate information, missing access, late approvals, platform action, or a change in client direction.</li></ul></> },
  { id: "ongoing-services", title: "Ongoing and recurring services", content: <p>To stop a recurring service, provide the notice required by the applicable agreement before the next service period. Cancellation prevents future work and billing after the effective date but does not normally refund a period that has begun or capacity already reserved. Advertising and platform campaigns may require separate shutdown steps and may continue incurring third-party charges until access permits completion.</p> },
  { id: "processing", title: "Refund review and processing timeframe", content: <><p>We aim to acknowledge a complete request within two business days and provide an eligibility decision within ten business days. Complex projects may require additional records; if so, we will explain the delay.</p><p>Approved refunds are initiated within ten business days after approval, using the original payment method where practical. Banks and payment providers may require additional time to post funds. We are not responsible for external processing delays, currency conversion differences, or payment-provider fees that are not returned to us.</p></> },
  { id: "disputes-contact", title: "Questions and billing disputes", content: <p>Contact us promptly at <a className="font-semibold text-ink underline underline-offset-4" href="mailto:hello@themarkgent.com">hello@themarkgent.com</a> with relevant proposals, invoices, approvals, and correspondence. We will review the request in good faith. This policy does not limit rights or remedies available under applicable law.</p> },
];

export default function RefundPolicyPage() { return <><Nav /><LegalDocument eyebrow="Legal" title="Refund Policy" summary="How service cancellations and refund requests are evaluated, including non-refundable work and processing timeframes." sections={sections} /><Footer /><CookieBanner /></>; }
